### PR TITLE
Hkube db migration

### PR DESCRIPTION
**Pull request by nassiharel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/3)

### CODE REVIEW

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/3)* status: 0 of 17 files reviewed, 7 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[lib/MongoDB/Collection.js, line 61 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl3F_LBBF0p22mzSez:-MMl3F_LBBF0p22mzSf-:b-invuac) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L61)):*
> ```JavaScript
>     }
> 
>     async create(options) {
> ```

options? what does it contain? 
also, why is it called options? it is a document not a configuration
if you want to be a generic function I suggest you add some type signature (a generic you get from the inheriting class or something) 
___
*[lib/MongoDB/Collection.js, line 68 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl2UukE_bzazGlO4fK:-MMl2UukE_bzazGlO4fL:b-uuifth) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L68)):*
> ```JavaScript
>              * OR
>              *
>              * We can set manually the _id `const _id = options[this.index];`
> ```

It is a very bad idea to manually set the _id, it is automatically indexed and contains extra useful data.
If you need some external id, just add a new field
___
*[lib/MongoDB/Collection.js, line 72 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl3kYW0FLVxoFG3wz7:-MMl3kYW0FLVxoFG3wz8:b-okrxd6) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L72)):*
> ```JavaScript
>              */
> 
>             await this.collection.insertOne({ ...options });
> ```

if you return the only the options back where do you get the _id from?
collection.insertOne should return the insertedId merge it into the object
___
*[lib/MongoDB/Collection.js, line 161 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl4zdj2X1mG9Vohd9W:-MMl4zdj2X1mG9Vohd9X:b-ldasge) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L161)):*
> ```JavaScript
>             return this.collection
>                 .find({ name: { $in: names } })
>                 .project({ ...projection })
> ```

why do you wrap the projection object and then destruct it back? why not just project(projection)?
___
*[lib/MongoDB/Collection.js, line 179 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl5IRS19liCcK0kouC:-MMl5IRS19liCcK0kouD:b-bq7toz) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L179)):*
> ```JavaScript
>         return this.collection
>             .find(query)
>             .project({ ...excludedFields, ...includedFields })
> ```

You cannot combine both included and excluded you need to pick one (mongo will throw an error) 
___
*[lib/MongoDB/Jobs.js, line 9 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl62xn8XQCQ2GYR9Yc:-MMl62xn8XQCQ2GYR9Yd:b-dyo1vd) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Jobs.js#L9)):*
> ```JavaScript
> 
>     /**
>      * @param {object} props
> ```

it is called job not props - update them to match and you'll get type validation
also I suggest you extract this signature to it's own typedef or .d file and it'll be re-usable
___
*[lib/MongoDB/Jobs.js, line 15 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl6RcS-9C3Vc7Zknm0:-MMl6RcS-9C3Vc7Zknm1:b-g145l2) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Jobs.js#L15)):*
> ```JavaScript
>      * @param {string} props.status
>      * @param {string} props.result
>      * @returns {Promise<DataSource>}
> ```

creating a job returns a datasource?

**Review by nassiharel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/3)* status: 0 of 17 files reviewed, 7 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[lib/MongoDB/Collection.js, line 61 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl3F_LBBF0p22mzSez:-MMlSm51-ziN-WLa75Q3:b-wis3x0) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L61)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

options? what does it contain? 
also, why is it called options? it is a document not a configuration
if you want to be a generic function I suggest you add some type signature (a generic you get from the inheriting class or something) 
</blockquote></details>

This is a draft PR, it's not ready for review.
 I have a lot more work to do
___
*[lib/MongoDB/Collection.js, line 161 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl4zdj2X1mG9Vohd9W:-MMlSdjqEuwTjoD51jvd:b-v45doh) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L161)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

why do you wrap the projection object and then destruct it back? why not just project(projection)?
</blockquote></details>

Yes, I saw it after push...
___
*[lib/MongoDB/Collection.js, line 179 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl5IRS19liCcK0kouC:-MMlSMXjBWkzfhV9NqRa:b-4jd4df) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L179)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

You cannot combine both included and excluded you need to pick one (mongo will throw an error) 
</blockquote></details>

Do you think I did not read the documentation?
(it will not throw if the excluded is `_id`)

**Review by nassiharel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/3)* status: 0 of 28 files reviewed, 7 unresolved discussions (waiting on @reggev)

___
*[lib/MongoDB/Collection.js, line 68 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl2UukE_bzazGlO4fK:-MN490L-A433VAnotDse:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L68)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

It is a very bad idea to manually set the _id, it is automatically indexed and contains extra useful data.
If you need some external id, just add a new field
</blockquote></details>

Done.
___
*[lib/MongoDB/Collection.js, line 72 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl3kYW0FLVxoFG3wz7:-MN4925Z7kjLehNH6Kza:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L72)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

if you return the only the options back where do you get the _id from?
collection.insertOne should return the insertedId merge it into the object
</blockquote></details>

Done.
___
*[lib/MongoDB/Jobs.js, line 9 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl62xn8XQCQ2GYR9Yc:-MN49H6PAYoHVBuFj9c3:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Jobs.js#L9)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

it is called job not props - update them to match and you'll get type validation
also I suggest you extract this signature to it's own typedef or .d file and it'll be re-usable
</blockquote></details>

Done.
___
*[lib/MongoDB/Jobs.js, line 15 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MMl6RcS-9C3Vc7Zknm0:-MN49Hl8DI56vZdFYT5C:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Jobs.js#L15)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

creating a job returns a datasource?
</blockquote></details>

Done.

**Review by nassiharel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/3)* status: 0 of 28 files reviewed, 8 unresolved discussions (waiting on @reggev)

___
*[lib/Algorithm.d.ts, line 6 at r2](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MN4EsdfDsWNFhPOcH6R:-MN4EsdfDsWNFhPOcH6S:b-97cs8r) ([raw file](https://github.com/kube-hpc/db.hkube/blob/1ea98d7ed078fccb2d81e2aa00ad3d8486f3d2e3/lib/Algorithm.d.ts#L6)):*
> ```XML
>     id?: Id;
>     name: string;
>     // impossible to list all available fields and also to maintain it...
> ```

Or we can use something like:
https://github.com/quicktype/quicktype

**Review by nassiharel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/3)* status: 0 of 28 files reviewed, 8 unresolved discussions (waiting on @reggev)

___
*[lib/Algorithm.d.ts, line 6 at r2](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MN4EsdfDsWNFhPOcH6R:-MN4FAED1MIgRZHcR90s:b-ylnhi7) ([raw file](https://github.com/kube-hpc/db.hkube/blob/1ea98d7ed078fccb2d81e2aa00ad3d8486f3d2e3/lib/Algorithm.d.ts#L6)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Or we can use something like:
https://github.com/quicktype/quicktype
</blockquote></details>

https://app.quicktype.io/

https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype

**Review by reggev — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/3)* status: 0 of 39 files reviewed, 11 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[.prettierrc.js, line 7 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MNJuirRCeMQAJ_byDyc:-MNJuirS9wnvnlt3ZmLf:bt8ua1c) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/.prettierrc.js#L7)):*
> ```JavaScript
>     arrowParens: 'avoid',
>     tabWidth: 4,
>     // printWidth: 180,
> ```

Can we please have a line length limit?
___
*[lib/Algorithm.d.ts, line 6 at r2](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MN4EsdfDsWNFhPOcH6R:-MNJutck5aRyzcZN-Bg8:b-dfjoqi) ([raw file](https://github.com/kube-hpc/db.hkube/blob/1ea98d7ed078fccb2d81e2aa00ad3d8486f3d2e3/lib/Algorithm.d.ts#L6)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

https://app.quicktype.io/
</blockquote></details>

You used it on the pipelines, and it looks really good, well documented and surprisingly clean and readable
Also, it can help us make everything consistent.
Great Idea!
___
*[lib/const/collections.js, line 1 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MNJrcZdCNEA7mMKy0GX:-MNJrcZeDwXeBG6lP9rM:bap7sq8) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/const/collections.js#L1)):*
> ```JavaScript
> module.exports = {
> ```

Why do we need an external const directory with the settings of each collection?
I think each collection should handle its own details in the init method with the relevant settings to itself it is more readable and easier to maintain.
also, what happens if you need more than one index? and why do we have an index row for un-indexed collections?
___
*[lib/MongoDB/Collection.js, line 49 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MNJw0mg-etphhIjnWo8:-MNJw0mh41Ju7DW_sj0v:b-uytpc1) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L49)):*
> ```JavaScript
>     }
> 
>     [removeId](entry) {
> ```

Why would you like to strip the _id an object? 
Just keep it, I think it might be a good idea to drop the other ids in the future -  the ones manually generated on the api server, this could be a good replacement (we can discuss this more if you'll like to)

**Review by nassiharel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/3)* status: 0 of 39 files reviewed, 11 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[.prettierrc.js, line 7 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MNJuirRCeMQAJ_byDyc:-MNMzE2f3agBbfD2_kxQ:b2ng5s1) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/.prettierrc.js#L7)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

Can we please have a line length limit?
</blockquote></details>


OK
___
*[lib/const/collections.js, line 1 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MNJrcZdCNEA7mMKy0GX:-MNMwVVx-fX2Kzethzc-:bn5ersb) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/const/collections.js#L1)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

Why do we need an external const directory with the settings of each collection?
I think each collection should handle its own details in the init method with the relevant settings to itself it is more readable and easier to maintain.
also, what happens if you need more than one index? and why do we have an index row for un-indexed collections?

</blockquote></details>

All collection settings should be in one place.
Where we have an index row for un-indexed collections?
___
*[lib/MongoDB/Collection.js, line 49 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/3#-MNJw0mg-etphhIjnWo8:-MNMxUo86J2W2V013tGC:b-9fwypv) ([raw file](https://github.com/kube-hpc/db.hkube/blob/9f615f4c75af1e017e2277c0a44347b250110a5d/lib/MongoDB/Collection.js#L49)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

Why would you like to strip the _id an object? 
Just keep it, I think it might be a good idea to drop the other ids in the future -  the ones manually generated on the api server, this could be a good replacement (we can discuss this more if you'll like to)
</blockquote></details>

I don't want that each object I create will have a mongo id, this id goes and travel the entire hkube flow, and it will increase the size of the objects, the mongo id is irrelevant because we have the API-Server logic to create and fetch by id for each entity.

**Pull request merged**
