### PR TITLE
Feat datasource aggregation

### PR DESCRIPTION
**Pull request by reggev**
this branch adds fetching the latest version for the relevant queries, it also adds a custom aggregation result for fetching all the datasets (adding some metadata)

---
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/2)

### CODE REVIEW

**Review by nassiharel — COMMENTED** [review]
> Reviewed 5 of 16 files at r1, 2 of 8 files at r2, 1 of 4 files at r3, 1 of 3 files at r4, 6 of 7 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/2)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @reggev)

___
*[lib/MongoDB/index.js, line 48 at r6](https://reviewable.io/reviews/kube-hpc/db.hkube/2#-MQlkmzA0J5YVDNkN8LS:-MQlkmzB7bR341tS-Dub:b-7c1j5r) ([raw file](https://github.com/kube-hpc/db.hkube/blob/163cb86e959ffbfdfd2812f899e2e4837a528f46/lib/MongoDB/index.js#L48)):*
> ```
> this.snapshots = new Snapshots(this.db, this.client);
> ```
maybe 
dataSources.snapshots 
and
dataSources.store

this is just pre-planning

**Review by nassiharel — COMMENTED** [review]
> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/2)* status: 21 of 23 files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[lib/MongoDB/Snapshots.js, line 16 at r7](https://reviewable.io/reviews/kube-hpc/db.hkube/2#-MQv-jw376Apkut0FRVm:-MQv-jw376Apkut0FRVn:b83fl4q) ([raw file](https://github.com/kube-hpc/db.hkube/blob/046f3336f0bb9364fb8ed164435eb4e244d84ac1/lib/MongoDB/Snapshots.js#L16)):*
> ```
> class Snapshots
> ```

Add tests

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/2)* status: 14 of 32 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[lib/MongoDB/index.js, line 48 at r6](https://reviewable.io/reviews/kube-hpc/db.hkube/2#-MQlkmzA0J5YVDNkN8LS:-MQvZ2LK3Opn8j7HbsA-:b-24tum1) ([raw file](https://github.com/kube-hpc/db.hkube/blob/163cb86e959ffbfdfd2812f899e2e4837a528f46/lib/MongoDB/index.js#L48)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> this.snapshots = new Snapshots(this.db, this.client);
> ```
maybe 
dataSources.snapshots 
and
dataSources.store

this is just pre-planning
</blockquote></details>

I don't see the benefit in doing this now...
___
*[lib/MongoDB/Snapshots.js, line 16 at r7](https://reviewable.io/reviews/kube-hpc/db.hkube/2#-MQv-jw376Apkut0FRVm:-MQvZWIGEcsR4Xld4Onz:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/046f3336f0bb9364fb8ed164435eb4e244d84ac1/lib/MongoDB/Snapshots.js#L16)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> class Snapshots
> ```

Add tests
</blockquote></details>

Done.

**Review by nassiharel — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 7 files at r5, 17 of 17 files at r8.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/2#-:-MQvjEy32FX7O08BqG5V:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
