### PR TITLE
Adding gateway

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)

### CODE REVIEW

**Review by nassiharel — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-:-MYnUcLyAE6Qxdyfftqs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[lib/MongoDB/Gateways.js, line 32 at r3](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYnrEHZ2vxMaFLvgOVK:-MYnrEH_2KbEKTYktIgL:b-17oyuf) ([raw file](https://github.com/kube-hpc/db.hkube/blob/3ba3f92c48f52c0488f1bc356575942c01110d47/lib/MongoDB/Gateways.js#L32)):*
> ```
> job, node,
> ```

jobId, nodeName
___
*[tests/common.js, line 191 at r3](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYnrUGlDbsJL9wXAFiM:-MYnrUGlDbsJL9wXAFiN:b8kftmt) ([raw file](https://github.com/kube-hpc/db.hkube/blob/3ba3f92c48f52c0488f1bc356575942c01110d47/tests/common.js#L191)):*
> ```
> job: 'jobID',
> ```
use uuid()
___
*[tests/gateway.test.js, line 17 at r3](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYnrX6H468M1q5uU_u4:-MYnrX6H468M1q5uU_u5:bagx4wq) ([raw file](https://github.com/kube-hpc/db.hkube/blob/3ba3f92c48f52c0488f1bc356575942c01110d47/tests/gateway.test.js#L17)):*
> ```
> it.only
> ```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

___
*[lib/MongoDB/Gateways.js, line 32 at r3](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYnrEHZ2vxMaFLvgOVK:-MYnvD0893oWp9tkmPae:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/3ba3f92c48f52c0488f1bc356575942c01110d47/lib/MongoDB/Gateways.js#L32)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> job, node,
> ```

jobId, nodeName
</blockquote></details>

Done.
___
*[tests/common.js, line 191 at r3](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYnrUGlDbsJL9wXAFiM:-MYnv5M5-CFMEA-oDzFY:bb6un1j) ([raw file](https://github.com/kube-hpc/db.hkube/blob/3ba3f92c48f52c0488f1bc356575942c01110d47/tests/common.js#L191)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> job: 'jobID',
> ```
use uuid()
</blockquote></details>

Done
___
*[tests/gateway.test.js, line 17 at r3](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYnrX6H468M1q5uU_u4:-MYnvAgOB4oxZ-Yx6uBQ:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/3ba3f92c48f52c0488f1bc356575942c01110d47/tests/gateway.test.js#L17)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> it.only
> ```

</blockquote></details>

Done.

**Review by nassiharel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[tests/gateway.test.js, line 9 at r4](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYoUa2CD0hmCIozD5kL:-MYoUa2D7FIUNLbUNHfC:b-l7bhqe) ([raw file](https://github.com/kube-hpc/db.hkube/blob/85b9e222067b0406e188e03733347e74c2c0d72d/tests/gateway.test.js#L9)):*
> ```
> describe.only
> ```
___
*[tests/gateway.test.js, line 56 at r4](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYoUrU9DK8DxXBGCDjt:-MYoUrUA1Lg7z7g7ZPgy:b-pu53fm) ([raw file](https://github.com/kube-hpc/db.hkube/blob/85b9e222067b0406e188e03733347e74c2c0d72d/tests/gateway.test.js#L56)):*
> ```
> let nodeName = uuid();
> ```
why not generate uuid inside `generateGateway`?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[tests/gateway.test.js, line 9 at r4](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYoUa2CD0hmCIozD5kL:-MYtHU1-ErC5-x0I_VZx:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/85b9e222067b0406e188e03733347e74c2c0d72d/tests/gateway.test.js#L9)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> describe.only
> ```

</blockquote></details>

Done.
___
*[tests/gateway.test.js, line 56 at r4](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYoUrU9DK8DxXBGCDjt:-MYtGFYq2eSSsYzEfjVz:b-cd02ll) ([raw file](https://github.com/kube-hpc/db.hkube/blob/85b9e222067b0406e188e03733347e74c2c0d72d/tests/gateway.test.js#L56)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> let nodeName = uuid();
> ```
why not generate uuid inside `generateGateway`?
</blockquote></details>

I need to know what is the id in order to fetch by the id.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[tests/gateway.test.js, line 56 at r4](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYoUrU9DK8DxXBGCDjt:-MYtJbY4Dae1jXjxSJNX:bcumrmx) ([raw file](https://github.com/kube-hpc/db.hkube/blob/85b9e222067b0406e188e03733347e74c2c0d72d/tests/gateway.test.js#L56)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I need to know what is the id in order to fetch by the id.
</blockquote></details>

I will create the uuid in the generateGateway

**Review by nassiharel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[tests/gateway.test.js, line 56 at r4](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYoUrU9DK8DxXBGCDjt:-MYtLF5z77H_cA7NX_mI:byb91op) ([raw file](https://github.com/kube-hpc/db.hkube/blob/85b9e222067b0406e188e03733347e74c2c0d72d/tests/gateway.test.js#L56)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I will create the uuid in the generateGateway
</blockquote></details>

but you aren't f fetching by the id

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[tests/gateway.test.js, line 59 at r5](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MZ6pBgYD40UvgVG88ne:-MZ6pBgZ0FUyfzeAJY-a:b-kk23ku) ([raw file](https://github.com/kube-hpc/db.hkube/blob/1528eca77c7eb05757e9961ec5a74f4b242a54a1/tests/gateway.test.js#L59)):*
> ```
>         nodeName = uuid();
>         jobId = uuid();
> ```

not relevant

**Review by nassiharel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[tests/gateway.test.js, line 24 at r5](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MZ6pzj_5BzHIUKsFgGp:-MZ6pzj_5BzHIUKsFgGq:b-90mjse) ([raw file](https://github.com/kube-hpc/db.hkube/blob/1528eca77c7eb05757e9961ec5a74f4b242a54a1/tests/gateway.test.js#L24)):*
> ```
>  jobId:gateway.jobId, nodeName:gateway.nodeName
> ```
You aren't formatting your code

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[tests/gateway.test.js, line 56 at r4](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MYoUrU9DK8DxXBGCDjt:-MZ6rt2l3bNTWtiWu-eH:bll92i9) ([raw file](https://github.com/kube-hpc/db.hkube/blob/85b9e222067b0406e188e03733347e74c2c0d72d/tests/gateway.test.js#L56)):*
> ```
> generateGateway
> ```
fetching by id here:
 const res2 = await db.gateways.search({ jobId:gateway.jobId, nodeName:gateway.nodeName });

"
___
*[tests/gateway.test.js, line 59 at r5](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MZ6pBgYD40UvgVG88ne:-MZ6sJEv1hZpOajKke1E:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/1528eca77c7eb05757e9961ec5a74f4b242a54a1/tests/gateway.test.js#L59)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>         nodeName = uuid();
>         jobId = uuid();
> ```

not relevant
</blockquote></details>

Done.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

___
*[tests/gateway.test.js, line 24 at r5](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-MZ6pzj_5BzHIUKsFgGp:-MZ6vP737ADnQmsCL1xf:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/1528eca77c7eb05757e9961ec5a74f4b242a54a1/tests/gateway.test.js#L24)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  jobId:gateway.jobId, nodeName:gateway.nodeName
> ```
You aren't formatting your code
</blockquote></details>

Done.

**Review by nassiharel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/14#-:-MZ6xEdtEfTIDpMiAdFS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
