### PR TITLE
add kind to delete

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/20)

### CODE REVIEW

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/20)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[lib/MongoDB/algorithms/store.js, line 104 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/20#-MadH6ct4O5q9GP58Dcg:-MadH6ct4O5q9GP58Dch:besqhju) ([raw file](https://github.com/kube-hpc/db.hkube/blob/be193ff8ccdbeff84902386b4732d8a10f72b50c/lib/MongoDB/algorithms/store.js#L104)):*
> ```
> kind = 'algorithm'
> ```
What about the current algorithms that have no `kind`, this method will succeed to delete them?
___
*[lib/MongoDB/algorithms/store.js, line 105 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/20#-MadGYN77t1EPxIGW3hs:-MadGYN77t1EPxIGW3ht:bpt6xrl) ([raw file](https://github.com/kube-hpc/db.hkube/blob/be193ff8ccdbeff84902386b4732d8a10f72b50c/lib/MongoDB/algorithms/store.js#L105)):*
> ```
> super.delete
> ```
The original issue that I saw was that this method will delete all algorithms if there is no algorithm name.
Now after this fix, this method will delete all algorithms by kind.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/20)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[lib/MongoDB/algorithms/store.js, line 104 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/20#-MadH6ct4O5q9GP58Dcg:-Mb5ubtd4t34wFFIGw_Y:b-v9kafy) ([raw file](https://github.com/kube-hpc/db.hkube/blob/be193ff8ccdbeff84902386b4732d8a10f72b50c/lib/MongoDB/algorithms/store.js#L104)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> kind = 'algorithm'
> ```
What about the current algorithms that have no `kind`, this method will succeed to delete them?
</blockquote></details>

Changes so that if no kind is provided it will delete all algorithms of the name
___
*[lib/MongoDB/algorithms/store.js, line 105 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/20#-MadGYN77t1EPxIGW3hs:-Mb5wdsB7QU1G58W96lT:b2uo5pg) ([raw file](https://github.com/kube-hpc/db.hkube/blob/be193ff8ccdbeff84902386b4732d8a10f72b50c/lib/MongoDB/algorithms/store.js#L105)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> super.delete
> ```
The original issue that I saw was that this method will delete all algorithms if there is no algorithm name.
Now after this fix, this method will delete all algorithms by kind.
</blockquote></details>

Checking that a name is provided before deleting

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/20)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[tests/algorithms.test.js, line 162 at r2](https://reviewable.io/reviews/kube-hpc/db.hkube/20#-MbjNHK0A7uHOWqDBGmq:-MbjNHK17RlsgzCkW3Ik:bph3uwl) ([raw file](https://github.com/kube-hpc/db.hkube/blob/8dd16d3b645cc923d918b9657cfbd06fdca04cb7/tests/algorithms.test.js#L162)):*
> ```JavaScript
>         await db.algorithms.create(algorithm);
> ```

it is nicer to not have empty lines

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/20)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[tests/algorithms.test.js, line 162 at r2](https://reviewable.io/reviews/kube-hpc/db.hkube/20#-MbjNHK0A7uHOWqDBGmq:-MbkfjY27xWUwhgiwHPw:b-896fix) ([raw file](https://github.com/kube-hpc/db.hkube/blob/8dd16d3b645cc923d918b9657cfbd06fdca04cb7/tests/algorithms.test.js#L162)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

it is nicer to not have empty lines
</blockquote></details>

Done.

**Pull request merged**
