### PR TITLE
add graph to job

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/10)

### CODE REVIEW

**Review by reggev — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/10)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

___
*[lib/MongoDB/Jobs.js, line 58 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/10#-MW3NN3hCzK8lZ7Yrg5g:-MW3NN3hCzK8lZ7Yrg5h:blfaadi) ([raw file](https://github.com/kube-hpc/db.hkube/blob/04d035e90bebb9c6e37ef115093a92947bf07df9/lib/MongoDB/Jobs.js#L58)):*
> ```JavaScript
>     async fetchGraph({ jobId }) {
>         const entry = await this._fetchJob({ jobId }, { graph: true });
>         return entry && { jobId, ...entry.graph };
> ```

Why did you destructure the entry graph?
maybe it'll be better to keep the structure to the original document

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/10)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @reggev)

___
*[lib/MongoDB/Jobs.js, line 58 at r1](https://reviewable.io/reviews/kube-hpc/db.hkube/10#-MW3NN3hCzK8lZ7Yrg5g:-MW3PbLA8xBJpi93LoZ2:b-myf5dk) ([raw file](https://github.com/kube-hpc/db.hkube/blob/04d035e90bebb9c6e37ef115093a92947bf07df9/lib/MongoDB/Jobs.js#L58)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

Why did you destructure the entry graph?
maybe it'll be better to keep the structure to the original document
</blockquote></details>

I considered it, but it is the same in all of the rest of the `fetch...` methods

**Review by reggev — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Review by nassiharel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/db.hkube/10#-:-MW3jtgL8GAQyKdWTOi2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
